language: php

php:
  - 7.4

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - wpu@hotmail.de
    on_success: change
    on_failure: change

before_script:
  - .ci/scripts/console.sh -s build -p $TRAVIS_PHP_VERSION

script:
  - >
    echo "Running code quality tests";
    .ci/scripts/console.sh -s quality -p $TRAVIS_PHP_VERSION

  - >
    echo "Running unit tests";
    .ci/scripts/console.sh -s unit -p $TRAVIS_PHP_VERSION

  - >
    echo "Running end to end tests";
    .ci/scripts/console.sh -s e2e -p $TRAVIS_PHP_VERSION
