services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  OmegaCode\JwtSecuredApiTwig\:
    resource: '../src/*'
    exclude: '../src/{Loader}'

  OmegaCode\JwtSecuredApiTwig\Subscriber\KernelSubscriber:
    arguments:
      - '@service_container'
    tags:
      - 'kernel.event_subscriber'

  Twig\Environment:
    synthetic: true
